import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  modulesSidebar: [
    {
      type: 'doc',
      id: 'modules/actionablemessages/index',
      label: 'ActionableMessages',
    },
    {
      type: 'category',
      label: 'Command Reference',
      items: [{ type: 'autogenerated', dirName: 'modules/actionablemessages/commands' }],
    },
  ],
};

export default sidebars;
